name: Skpr Setup
description: Setup the Skpr client
runs:
  using: composite
  steps:
    - id: skpr-setup
      run: |
        wget -q https://packages.skpr.io/apt/packages.skpr.io.pub -O- | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/packages.skpr.io.pub > /dev/null
        echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.skpr.io.pub] https://packages.skpr.io/apt stable main" | sudo tee -a /etc/apt/sources.list.d/skpr.list > /dev/null
        sudo apt update && sudo apt install skpr
      shell: bash
