name: Skpr Setup
description: Setup the Skpr client
runs:
  using: composite
  steps:
    - id: skpr-setup
      run: |
        download_url=$(wget -q -O - 'https://api.github.com/repos/skpr/cli/releases/latest' | jq -r '.assets[] | select(.name|endswith("linux_amd64.deb")).browser_download_url')
        echo "Downloading skpr cli from $download_url"
        wget -q $download_url -O skpr.deb
        echo "Installing skpr cli"
        sudo apt install skpr.deb
      shell: bash
